// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserAuth = "user_auth"

// UserAuth mapped from table <user_auth>
type UserAuth struct {
	Token     string `gorm:"column:token;primaryKey" json:"token"`
	UserID    int32  `gorm:"column:user_id;not null" json:"user_id"`
	LoginIP   []byte `gorm:"column:login_ip;not null" json:"login_ip"`
	LoginTime string `gorm:"column:login_time;not null;default:current_timestamp()" json:"login_time"`
}

// TableName UserAuth's table name
func (*UserAuth) TableName() string {
	return TableNameUserAuth
}
