// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID               int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PrivateKey       string `gorm:"column:private_key" json:"private_key"`
	Username         string `gorm:"column:username;not null" json:"username"`
	Nickname         string `gorm:"column:nickname;not null;default:user" json:"nickname"`
	Avatar           string `gorm:"column:avatar" json:"avatar"`
	Password         string `gorm:"column:password;not null" json:"password"`
	Sex              string `gorm:"column:sex;not null;default:未知" json:"sex"`
	Email            string `gorm:"column:email" json:"email"`
	Phone            string `gorm:"column:phone" json:"phone"`
	Vip              string `gorm:"column:vip;not null;default:current_timestamp()" json:"vip"`
	Svip             string `gorm:"column:svip;not null;default:current_timestamp()" json:"svip"`
	Gold             int32  `gorm:"column:gold;not null" json:"gold"`
	Cny              int32  `gorm:"column:cny;not null" json:"cny"`
	MembershipPoints int32  `gorm:"column:membership_points;not null" json:"membership_points"`
	SafetyScore      int32  `gorm:"column:safety_score;not null;default:500" json:"safety_score"`
	LoginIP          []byte `gorm:"column:login_ip" json:"login_ip"`
	UserGroup        int32  `gorm:"column:user_group;not null;default:1" json:"user_group"`
	State            int32  `gorm:"column:state;not null;default:1" json:"state"`
	CreateTime       string `gorm:"column:create_time;not null;default:current_timestamp()" json:"create_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
